# Generated by Django 5.1.7 on 2025-03-26 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkme', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.TextField(blank=True, db_column='Actor', null=True)),
                ('movie', models.TextField(blank=True, db_column='Movie', null=True)),
            ],
            options={
                'db_table': 'linkme',
                'managed': False,
            },
        ),
    ]
