# Generated by Django 5.1.7 on 2025-03-26 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linkme', '0002_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'managed': True},
        ),
    ]
